# fmt: off
ALL_TAGS = {
    10: {"name": "Cars", "category": "Theme-Other-Vehicle", "isAdult": False},
    15: {"name": "Demons", "category": "Cast-Traits", "isAdult": False},
    23: {"name": "Female Harem", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    25: {"name": "Historical", "category": "Setting-Time", "isAdult": False},
    27: {"name": "Josei", "category": "Demographic", "isAdult": False},
    28: {"name": "Kids", "category": "Demographic", "isAdult": False},
    29: {"name": "Magic", "category": "Theme-Fantasy", "isAdult": False},
    30: {"name": "Martial Arts", "category": "Theme-Action", "isAdult": False, "mood": "hype"},
    34: {"name": "Military", "category": "Theme-Other-Organisations", "isAdult": False, "intensity": "heavy"},
    39: {"name": "Parody", "category": "Theme-Comedy", "isAdult": False, "mood": "funny", "intensity": "light"},
    40: {"name": "Police", "category": "Theme-Other-Organisations", "isAdult": False},
    43: {"name": "Swordplay", "category": "Theme-Action", "isAdult": False, "mood": "hype"},
    46: {"name": "School", "category": "Setting-Scene", "isAdult": False},
    50: {"name": "Seinen", "category": "Demographic", "isAdult": False},
    53: {"name": "Shoujo", "category": "Demographic", "isAdult": False},
    56: {"name": "Shounen", "category": "Demographic", "isAdult": False},
    63: {"name": "Space", "category": "Setting-Universe", "isAdult": False},
    66: {"name": "Super Power", "category": "Theme-Fantasy", "isAdult": False, "mood": "hype"},
    74: {"name": "Vampire", "category": "Cast-Traits", "isAdult": False},
    75: {"name": "Boys' Love", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    76: {"name": "Yuri", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    77: {"name": "Gender Bending", "category": "Theme-Other", "isAdult": False},
    80: {"name": "Satire", "category": "Theme-Comedy", "isAdult": False, "mood": "funny", "intensity": "light"},
    81: {"name": "Iyashikei", "category": "Theme-Slice of Life", "isAdult": False, "mood": "chill", "intensity": "light"},
    82: {"name": "Male Protagonist", "category": "Cast-Main Cast", "isAdult": False},
    83: {"name": "Slapstick", "category": "Theme-Comedy", "isAdult": False, "mood": "funny", "intensity": "light"},
    84: {"name": "School Club", "category": "Setting-Scene", "isAdult": False},
    85: {"name": "Tragedy", "category": "Theme-Drama", "isAdult": False, "mood": "emotional", "intensity": "heavy"},
    86: {"name": "Primarily Female Cast", "category": "Cast-Main Cast", "isAdult": False},
    87: {"name": "Family Life", "category": "Theme-Slice of Life", "isAdult": False, "mood": "chill", "intensity": "light"},
    88: {"name": "Primarily Male Cast", "category": "Cast-Main Cast", "isAdult": False},
    89: {"name": "Full CGI", "category": "Technical", "isAdult": False},
    90: {"name": "CGI", "category": "Technical", "isAdult": False},
    91: {"name": "Gambling", "category": "Theme-Other", "isAdult": False, "mood": "cerebral", "intensity": "moderate"},
    92: {"name": "Cute Girls Doing Cute Things", "category": "Theme-Slice of Life", "isAdult": False, "mood": "chill", "intensity": "light"},
    93: {"name": "Post-Apocalyptic", "category": "Setting-Universe", "isAdult": False},
    94: {"name": "Gore", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    95: {"name": "Steampunk", "category": "Theme-Fantasy", "isAdult": False, "mood": "adventurous"},
    96: {"name": "Time Manipulation", "category": "Theme-Sci-Fi", "isAdult": False},
    97: {"name": "Otaku Culture", "category": "Theme-Other", "isAdult": False},
    98: {"name": "Female Protagonist", "category": "Cast-Main Cast", "isAdult": False},
    99: {"name": "Henshin", "category": "Theme-Fantasy", "isAdult": False},
    100: {"name": "Nudity", "category": "Cast-Traits", "isAdult": False},
    101: {"name": "Battle Royale", "category": "Theme-Action", "isAdult": False, "mood": "hype"},
    102: {"name": "Coming of Age", "category": "Theme-Drama", "isAdult": False, "mood": "emotional", "intensity": "moderate"},
    103: {"name": "Politics", "category": "Theme-Other", "isAdult": False, "mood": "cerebral", "intensity": "moderate"},
    104: {"name": "Anti-Hero", "category": "Cast-Main Cast", "isAdult": False},
    105: {"name": "Ensemble Cast", "category": "Cast-Main Cast", "isAdult": False},
    106: {"name": "Gangs", "category": "Theme-Other-Organisations", "isAdult": False, "intensity": "moderate"},
    107: {"name": "Mafia", "category": "Theme-Other-Organisations", "isAdult": False, "intensity": "moderate"},
    108: {"name": "Cyberpunk", "category": "Theme-Sci-Fi", "isAdult": False},
    109: {"name": "Primarily Adult Cast", "category": "Cast-Main Cast", "isAdult": False},
    110: {"name": "Band", "category": "Theme-Arts-Music", "isAdult": False},
    111: {"name": "War", "category": "Theme-Other", "isAdult": False, "intensity": "heavy"},
    112: {"name": "Virtual World", "category": "Setting-Universe", "isAdult": False},
    113: {"name": "Nekomimi", "category": "Cast-Traits", "isAdult": False},
    115: {"name": "Idol", "category": "Cast-Traits", "isAdult": False},
    116: {"name": "Volleyball", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    117: {"name": "Mahjong", "category": "Theme-Game-Card & Board Game", "isAdult": False, "mood": "sporty"},
    118: {"name": "Drawing", "category": "Theme-Arts", "isAdult": False},
    120: {"name": "Table Tennis", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    121: {"name": "Shogi", "category": "Theme-Game-Card & Board Game", "isAdult": False, "mood": "sporty"},
    122: {"name": "Trains", "category": "Theme-Other-Vehicle", "isAdult": False},
    123: {"name": "Male Harem", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    124: {"name": "Netorare", "category": "Sexual Content", "isAdult": True},
    125: {"name": "Nakadashi", "category": "Sexual Content", "isAdult": True},
    126: {"name": "Boobjob", "category": "Sexual Content", "isAdult": True},
    127: {"name": "Public Sex", "category": "Sexual Content", "isAdult": True},
    128: {"name": "Incest", "category": "Sexual Content", "isAdult": True},
    129: {"name": "Defloration", "category": "Sexual Content", "isAdult": True},
    130: {"name": "Facial", "category": "Sexual Content", "isAdult": True},
    131: {"name": "Masturbation", "category": "Sexual Content", "isAdult": True},
    132: {"name": "Threesome", "category": "Sexual Content", "isAdult": True},
    133: {"name": "Sex Toys", "category": "Sexual Content", "isAdult": True},
    134: {"name": "Fellatio", "category": "Sexual Content", "isAdult": True},
    135: {"name": "Cunnilingus", "category": "Sexual Content", "isAdult": True},
    136: {"name": "Flat Chest", "category": "Sexual Content", "isAdult": True},
    137: {"name": "Large Breasts", "category": "Sexual Content", "isAdult": True},
    138: {"name": "Age Gap", "category": "Theme-Romance", "isAdult": False},
    139: {"name": "Love Triangle", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    140: {"name": "Educational", "category": "Theme-Other", "isAdult": False},
    142: {"name": "Food", "category": "Theme-Arts", "isAdult": False, "mood": "chill", "intensity": "light"},
    143: {"name": "Survival", "category": "Theme-Other", "isAdult": False, "mood": "dark"},
    144: {"name": "Meta", "category": "Theme-Other", "isAdult": False},
    145: {"name": "Work", "category": "Setting-Scene", "isAdult": False},
    146: {"name": "Alternate Universe", "category": "Setting-Universe", "isAdult": False},
    147: {"name": "Afterlife", "category": "Setting-Universe", "isAdult": False},
    148: {"name": "Football", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    149: {"name": "Baseball", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    150: {"name": "Swimming", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    151: {"name": "Cycling", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    152: {"name": "Zombie", "category": "Cast-Traits", "isAdult": False},
    153: {"name": "Time Skip", "category": "Setting-Time", "isAdult": False},
    154: {"name": "Body Swapping", "category": "Theme-Fantasy", "isAdult": False},
    155: {"name": "Rape", "category": "Sexual Content", "isAdult": True},
    156: {"name": "Achronological Order", "category": "Setting-Time", "isAdult": False},
    157: {"name": "Guns", "category": "Theme-Action", "isAdult": False},
    158: {"name": "Crossover", "category": "Theme-Other", "isAdult": False},
    159: {"name": "Super Robot", "category": "Theme-Sci-Fi-Mecha", "isAdult": False},
    160: {"name": "Real Robot", "category": "Theme-Sci-Fi-Mecha", "isAdult": False},
    161: {"name": "Bar", "category": "Setting-Scene", "isAdult": False},
    162: {"name": "Space Opera", "category": "Theme-Sci-Fi", "isAdult": False, "mood": "adventurous"},
    163: {"name": "Yandere", "category": "Cast-Traits", "isAdult": False},
    164: {"name": "Tsundere", "category": "Cast-Traits", "isAdult": False},
    165: {"name": "Teacher", "category": "Cast-Traits", "isAdult": False},
    167: {"name": "Airsoft", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    169: {"name": "Boxing", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    170: {"name": "Fitness", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    171: {"name": "Bullying", "category": "Theme-Drama", "isAdult": False, "mood": "emotional", "intensity": "heavy"},
    172: {"name": "Superhero", "category": "Theme-Fantasy", "isAdult": False, "mood": "hype"},
    173: {"name": "Motorcycles", "category": "Theme-Other-Vehicle", "isAdult": False},
    174: {"name": "Tanks", "category": "Theme-Other-Vehicle", "isAdult": False},
    175: {"name": "Robots", "category": "Cast-Traits", "isAdult": False},
    176: {"name": "Mopeds", "category": "Theme-Other-Vehicle", "isAdult": False},
    178: {"name": "Card Battle", "category": "Theme-Game-Card & Board Game", "isAdult": False, "mood": "sporty"},
    179: {"name": "Witch", "category": "Cast-Traits", "isAdult": False},
    180: {"name": "Watersports", "category": "Sexual Content", "isAdult": True},
    181: {"name": "Human Pet", "category": "Sexual Content", "isAdult": True},
    182: {"name": "Karuta", "category": "Theme-Game-Card & Board Game", "isAdult": False, "mood": "sporty"},
    183: {"name": "Poker", "category": "Theme-Game-Card & Board Game", "isAdult": False, "mood": "sporty"},
    185: {"name": "Anal Sex", "category": "Sexual Content", "isAdult": True},
    186: {"name": "Crossdressing", "category": "Cast-Traits", "isAdult": False},
    187: {"name": "MILF", "category": "Sexual Content", "isAdult": True},
    188: {"name": "Futanari", "category": "Sexual Content", "isAdult": True},
    189: {"name": "Tentacles", "category": "Sexual Content", "isAdult": True},
    190: {"name": "Prostitution", "category": "Sexual Content", "isAdult": True},
    191: {"name": "Aliens", "category": "Cast-Traits", "isAdult": False},
    192: {"name": "Basketball", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    193: {"name": "Episodic", "category": "Technical", "isAdult": False},
    194: {"name": "Tennis", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    195: {"name": "Photography", "category": "Theme-Arts", "isAdult": False},
    198: {"name": "Foreign", "category": "Setting-Scene", "isAdult": False},
    199: {"name": "Yakuza", "category": "Theme-Other-Organisations", "isAdult": False, "intensity": "moderate"},
    201: {"name": "Pirates", "category": "Cast-Traits", "isAdult": False, "mood": "adventurous"},
    204: {"name": "Calligraphy", "category": "Theme-Arts", "isAdult": False},
    206: {"name": "4-koma", "category": "Technical", "isAdult": False},
    207: {"name": "Full Color", "category": "Technical", "isAdult": False},
    208: {"name": "Mythology", "category": "Theme-Fantasy", "isAdult": False},
    209: {"name": "Dancing", "category": "Theme-Arts-Music", "isAdult": False},
    212: {"name": "Fishing", "category": "Theme-Game-Sport", "isAdult": False, "mood": "chill", "intensity": "light"},
    214: {"name": "Triads", "category": "Theme-Other-Organisations", "isAdult": False, "intensity": "moderate"},
    215: {"name": "POV", "category": "Technical", "isAdult": False},
    217: {"name": "Dystopian", "category": "Setting-Time", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    220: {"name": "Ghost", "category": "Cast-Traits", "isAdult": False},
    221: {"name": "Rugby", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    224: {"name": "Dragons", "category": "Cast-Traits", "isAdult": False},
    226: {"name": "Fugitive", "category": "Theme-Action", "isAdult": False},
    227: {"name": "Classic Literature", "category": "Theme-Arts", "isAdult": False, "mood": "cerebral"},
    228: {"name": "Ice Skating", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    231: {"name": "Wrestling", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    233: {"name": "Youkai", "category": "Theme-Fantasy", "isAdult": False},
    235: {"name": "Badminton", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    239: {"name": "Biographical", "category": "Theme-Other", "isAdult": False},
    240: {"name": "Amnesia", "category": "Cast-Traits", "isAdult": False, "intensity": "moderate"},
    242: {"name": "Flash", "category": "Technical", "isAdult": False},
    243: {"name": "Reincarnation", "category": "Theme-Other", "isAdult": False, "mood": "adventurous"},
    244: {"name": "Isekai", "category": "Theme-Fantasy", "isAdult": False, "mood": "adventurous"},
    246: {"name": "Bondage", "category": "Sexual Content", "isAdult": True},
    247: {"name": "Slavery", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    248: {"name": "Economics", "category": "Theme-Other", "isAdult": False, "mood": "cerebral", "intensity": "moderate"},
    249: {"name": "Maids", "category": "Cast-Traits", "isAdult": False},
    250: {"name": "Rural", "category": "Setting-Scene", "isAdult": False},
    251: {"name": "Archery", "category": "Theme-Action", "isAdult": False},
    252: {"name": "Revenge", "category": "Theme-Drama", "isAdult": False, "intensity": "heavy"},
    253: {"name": "Gods", "category": "Cast-Traits", "isAdult": False},
    254: {"name": "Kemonomimi", "category": "Cast-Traits", "isAdult": False},
    255: {"name": "Ninja", "category": "Cast-Traits", "isAdult": False},
    259: {"name": "Monster Girl", "category": "Cast-Traits", "isAdult": False},
    262: {"name": "Outdoor Activities", "category": "Setting-Scene", "isAdult": False, "mood": "chill", "intensity": "light"},
    264: {"name": "Athletics", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    265: {"name": "Musical Theater", "category": "Theme-Arts-Music", "isAdult": False},
    267: {"name": "Chuunibyou", "category": "Cast-Traits", "isAdult": False},
    276: {"name": "Kaiju", "category": "Theme-Fantasy", "isAdult": False, "mood": "hype"},
    279: {"name": "Ahegao", "category": "Sexual Content", "isAdult": True},
    280: {"name": "Netorase", "category": "Sexual Content", "isAdult": True},
    281: {"name": "Surreal Comedy", "category": "Theme-Comedy", "isAdult": False, "mood": "funny", "intensity": "light"},
    282: {"name": "Hikikomori", "category": "Cast-Traits", "isAdult": False},
    285: {"name": "Terrorism", "category": "Theme-Other", "isAdult": False, "intensity": "heavy"},
    291: {"name": "Samurai", "category": "Cast-Traits", "isAdult": False},
    294: {"name": "Bisexual", "category": "Cast-Traits", "isAdult": False},
    303: {"name": "Wuxia", "category": "Theme-Fantasy", "isAdult": False, "mood": "adventurous"},
    305: {"name": "Ships", "category": "Theme-Other-Vehicle", "isAdult": False, "mood": "adventurous"},
    308: {"name": "Video Games", "category": "Theme-Game", "isAdult": False},
    309: {"name": "Blackmail", "category": "Theme-Other", "isAdult": False, "intensity": "moderate"},
    310: {"name": "Espionage", "category": "Theme-Action", "isAdult": False, "mood": "cerebral", "intensity": "moderate"},
    311: {"name": "Rehabilitation", "category": "Theme-Drama", "isAdult": False, "mood": "emotional", "intensity": "moderate"},
    314: {"name": "American Football", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    315: {"name": "Ashikoki", "category": "Sexual Content", "isAdult": True},
    316: {"name": "Netori", "category": "Sexual Content", "isAdult": True},
    317: {"name": "Handjob", "category": "Sexual Content", "isAdult": True},
    318: {"name": "Voyeur", "category": "Sexual Content", "isAdult": True},
    321: {"name": "Urban Fantasy", "category": "Setting-Universe", "isAdult": False},
    322: {"name": "Assassins", "category": "Theme-Other-Organisations", "isAdult": False},
    323: {"name": "Stop Motion", "category": "Technical", "isAdult": False},
    324: {"name": "Chibi", "category": "Theme-Other", "isAdult": False, "mood": "funny", "intensity": "light"},
    325: {"name": "Puppetry", "category": "Technical", "isAdult": False},
    326: {"name": "Cultivation", "category": "Theme-Fantasy", "isAdult": False, "mood": "adventurous"},
    327: {"name": "Noir", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    328: {"name": "Cosplay", "category": "Cast-Traits", "isAdult": False},
    334: {"name": "Agender", "category": "Cast-Traits", "isAdult": False},
    335: {"name": "Tanned Skin", "category": "Cast-Traits", "isAdult": False},
    341: {"name": "No Dialogue", "category": "Technical", "isAdult": False},
    342: {"name": "Environmental", "category": "Theme-Other", "isAdult": False},
    355: {"name": "Aviation", "category": "Theme-Other-Vehicle", "isAdult": False},
    356: {"name": "Gyaru", "category": "Cast-Traits", "isAdult": False},
    359: {"name": "Irrumatio", "category": "Sexual Content", "isAdult": True},
    360: {"name": "Sumata", "category": "Sexual Content", "isAdult": True},
    364: {"name": "Augmented Reality", "category": "Setting-Universe", "isAdult": False},
    365: {"name": "Memory Manipulation", "category": "Theme-Other", "isAdult": False, "intensity": "moderate"},
    380: {"name": "Virginity", "category": "Sexual Content", "isAdult": True},
    386: {"name": "Software Development", "category": "Theme-Other", "isAdult": False, "mood": "cerebral"},
    387: {"name": "Scat", "category": "Sexual Content", "isAdult": True},
    391: {"name": "Philosophy", "category": "Theme-Other", "isAdult": False, "mood": "cerebral", "intensity": "heavy"},
    394: {"name": "Writing", "category": "Theme-Arts", "isAdult": False, "mood": "cerebral"},
    395: {"name": "Delinquents", "category": "Cast-Traits", "isAdult": False, "intensity": "moderate"},
    397: {"name": "Pregnancy", "category": "Theme-Other", "isAdult": False},
    400: {"name": "Fairy Tale", "category": "Theme-Fantasy", "isAdult": False},
    404: {"name": "College", "category": "Setting-Scene", "isAdult": False},
    410: {"name": "Fashion", "category": "Theme-Arts", "isAdult": False},
    433: {"name": "Animals", "category": "Theme-Other", "isAdult": False},
    437: {"name": "Lacrosse", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    443: {"name": "Go", "category": "Theme-Game-Card & Board Game", "isAdult": False, "mood": "sporty"},
    446: {"name": "Primarily Child Cast", "category": "Cast-Main Cast", "isAdult": False},
    456: {"name": "Conspiracy", "category": "Theme-Drama", "isAdult": False, "mood": "cerebral", "intensity": "heavy"},
    466: {"name": "Lost Civilization", "category": "Theme-Other", "isAdult": False, "mood": "adventurous"},
    468: {"name": "Shrine Maiden", "category": "Cast-Traits", "isAdult": False},
    471: {"name": "Anthology", "category": "Technical", "isAdult": False},
    476: {"name": "Circus", "category": "Setting-Scene", "isAdult": False},
    480: {"name": "Goblin", "category": "Cast-Traits", "isAdult": False},
    481: {"name": "Rakugo", "category": "Theme-Arts", "isAdult": False, "mood": "cerebral"},
    482: {"name": "Ero Guro", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    483: {"name": "LGBTQ+ Themes", "category": "Theme-Other", "isAdult": False, "mood": "emotional"},
    488: {"name": "Age Regression", "category": "Cast-Traits", "isAdult": False},
    489: {"name": "Drugs", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    490: {"name": "Anachronism", "category": "Setting-Time", "isAdult": False},
    494: {"name": "Twins", "category": "Cast-Traits", "isAdult": False},
    499: {"name": "Skeleton", "category": "Cast-Traits", "isAdult": False},
    505: {"name": "Advertisement", "category": "Technical", "isAdult": False},
    513: {"name": "Tokusatsu", "category": "Theme-Sci-Fi", "isAdult": False},
    516: {"name": "Language Barrier", "category": "Theme-Other", "isAdult": False},
    517: {"name": "Artificial Intelligence", "category": "Cast-Traits", "isAdult": False, "mood": "cerebral"},
    519: {"name": "Autobiographical", "category": "Theme-Other", "isAdult": False},
    532: {"name": "Golf", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    533: {"name": "Omegaverse", "category": "Setting-Universe", "isAdult": True},
    534: {"name": "Werewolf", "category": "Cast-Traits", "isAdult": False},
    536: {"name": "Dissociative Identities", "category": "Cast-Traits", "isAdult": False, "intensity": "moderate"},
    548: {"name": "Acting", "category": "Theme-Arts", "isAdult": False},
    558: {"name": "Mermaid", "category": "Cast-Traits", "isAdult": False},
    586: {"name": "Cult", "category": "Theme-Other-Organisations", "isAdult": False, "intensity": "moderate"},
    593: {"name": "Oiran", "category": "Cast-Traits", "isAdult": False},
    595: {"name": "Urban", "category": "Setting-Scene", "isAdult": False},
    598: {"name": "Elf", "category": "Cast-Traits", "isAdult": False},
    604: {"name": "Dungeon", "category": "Setting-Scene", "isAdult": False, "mood": "adventurous"},
    613: {"name": "Firefighters", "category": "Theme-Other-Organisations", "isAdult": False},
    614: {"name": "Nun", "category": "Cast-Traits", "isAdult": False},
    615: {"name": "Death Game", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    618: {"name": "Vikings", "category": "Cast-Traits", "isAdult": False},
    622: {"name": "Asexual", "category": "Cast-Traits", "isAdult": False},
    623: {"name": "Astronomy", "category": "Theme-Other", "isAdult": False},
    624: {"name": "Vore", "category": "Sexual Content", "isAdult": True},
    629: {"name": "Armpits", "category": "Sexual Content", "isAdult": True},
    630: {"name": "Sweat", "category": "Sexual Content", "isAdult": True},
    631: {"name": "Feet", "category": "Sexual Content", "isAdult": True},
    632: {"name": "Centaur", "category": "Cast-Traits", "isAdult": False},
    636: {"name": "Cosmic Horror", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    639: {"name": "Body Horror", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    646: {"name": "Cheerleading", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    648: {"name": "Crime", "category": "Theme-Other", "isAdult": False, "mood": "cerebral", "intensity": "heavy"},
    649: {"name": "Teens' Love", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    650: {"name": "Lactation", "category": "Sexual Content", "isAdult": True},
    651: {"name": "Asphyxiation", "category": "Sexual Content", "isAdult": True},
    652: {"name": "Amputation", "category": "Sexual Content", "isAdult": True},
    653: {"name": "Office Lady", "category": "Cast-Traits", "isAdult": False},
    654: {"name": "Denpa", "category": "Theme-Other", "isAdult": False, "mood": "dark"},
    658: {"name": "Dullahan", "category": "Cast-Traits", "isAdult": False},
    659: {"name": "Medicine", "category": "Theme-Other", "isAdult": False},
    665: {"name": "Succubus", "category": "Cast-Traits", "isAdult": False},
    678: {"name": "Surfing", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    683: {"name": "Rotoscoping", "category": "Technical", "isAdult": False},
    694: {"name": "Detective", "category": "Cast-Traits", "isAdult": False, "mood": "cerebral", "intensity": "moderate"},
    704: {"name": "Dinosaurs", "category": "Cast-Traits", "isAdult": False},
    710: {"name": "Achromatic", "category": "Technical", "isAdult": False},
    723: {"name": "Sadism", "category": "Sexual Content", "isAdult": True},
    772: {"name": "Shapeshifting", "category": "Theme-Fantasy", "isAdult": False},
    774: {"name": "Chimera", "category": "Cast-Traits", "isAdult": False},
    779: {"name": "Kuudere", "category": "Cast-Traits", "isAdult": False},
    780: {"name": "Ojou-sama", "category": "Cast-Traits", "isAdult": False},
    792: {"name": "E-Sports", "category": "Theme-Game", "isAdult": False, "mood": "sporty"},
    801: {"name": "Cyborg", "category": "Cast-Traits", "isAdult": False},
    809: {"name": "Skateboarding", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    811: {"name": "Scuba Diving", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    812: {"name": "Butler", "category": "Cast-Traits", "isAdult": False},
    830: {"name": "Group Sex", "category": "Sexual Content", "isAdult": True},
    845: {"name": "Rimjob", "category": "Sexual Content", "isAdult": True},
    857: {"name": "Villainess", "category": "Cast-Traits", "isAdult": False, "mood": "adventurous"},
    870: {"name": "Cannibalism", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    874: {"name": "Pandemic", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    901: {"name": "Exhibitionism", "category": "Sexual Content", "isAdult": True},
    909: {"name": "Agriculture", "category": "Theme-Slice of Life", "isAdult": False, "mood": "chill", "intensity": "light"},
    931: {"name": "Tomboy", "category": "Cast-Traits", "isAdult": False},
    949: {"name": "Parkour", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    999: {"name": "Masochism", "category": "Sexual Content", "isAdult": True},
    1038: {"name": "DILF", "category": "Sexual Content", "isAdult": True},
    1039: {"name": "Scissoring", "category": "Sexual Content", "isAdult": True},
    1045: {"name": "Heterosexual", "category": "Theme-Romance", "isAdult": False, "emotional": "true"},
    1046: {"name": "Suicide", "category": "Theme-Drama", "isAdult": False, "mood": "emotional", "intensity": "heavy"},
    1047: {"name": "VTuber", "category": "Cast-Traits", "isAdult": False},
    1052: {"name": "Adoption", "category": "Theme-Other", "isAdult": False, "mood": "emotional"},
    1063: {"name": "Cute Boys Doing Cute Things", "category": "Theme-Slice of Life", "isAdult": False, "mood": "chill", "intensity": "light"},
    1068: {"name": "Angels", "category": "Cast-Traits", "isAdult": False},
    1080: {"name": "Sumo", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    1090: {"name": "Monster Boy", "category": "Cast-Traits", "isAdult": False},
    1091: {"name": "Religion", "category": "Theme-Other", "isAdult": False, "intensity": "moderate"},
    1102: {"name": "Inseki", "category": "Sexual Content", "isAdult": True},
    1105: {"name": "Judo", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    1121: {"name": "Torture", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    1132: {"name": "Fencing", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    1140: {"name": "Makeup", "category": "Theme-Arts", "isAdult": False},
    1146: {"name": "Femdom", "category": "Sexual Content", "isAdult": True},
    1165: {"name": "Transgender", "category": "Cast-Traits", "isAdult": False},
    1219: {"name": "Disability", "category": "Cast-Traits", "isAdult": False, "mood": "emotional", "intensity": "heavy"},
    1228: {"name": "Primarily Teen Cast", "category": "Cast-Main Cast", "isAdult": False},
    1234: {"name": "Deepthroat", "category": "Sexual Content", "isAdult": True},
    1235: {"name": "Squirting", "category": "Sexual Content", "isAdult": True},
    1243: {"name": "Necromancy", "category": "Theme-Fantasy", "isAdult": False, "mood": "dark"},
    1273: {"name": "Cumflation", "category": "Sexual Content", "isAdult": True},
    1277: {"name": "Found Family", "category": "Theme-Other", "isAdult": False, "mood": "emotional"},
    1291: {"name": "Alchemy", "category": "Theme-Fantasy", "isAdult": False},
    1292: {"name": "Spearplay", "category": "Theme-Action", "isAdult": False},
    1304: {"name": "Anthropomorphism", "category": "Cast-Traits", "isAdult": False},
    1310: {"name": "Travel", "category": "Theme-Other", "isAdult": False, "mood": "adventurous"},
    1327: {"name": "Royal Affairs", "category": "Theme-Other", "isAdult": False},
    1337: {"name": "Non-fiction", "category": "Technical", "isAdult": False},
    1342: {"name": "Clone", "category": "Cast-Traits", "isAdult": False},
    1361: {"name": "Mixed Gender Harem", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    1367: {"name": "Hypersexuality", "category": "Sexual Content", "isAdult": True},
    1379: {"name": "Homeless", "category": "Cast-Traits", "isAdult": False, "intensity": "heavy"},
    1382: {"name": "Orphan", "category": "Cast-Traits", "isAdult": False, "intensity": "moderate", "mood": "emotional"},
    1396: {"name": "Handball", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    1403: {"name": "Class Struggle", "category": "Theme-Drama", "isAdult": False, "mood": "cerebral", "intensity": "heavy"},
    1419: {"name": "Kingdom Management", "category": "Theme-Drama", "isAdult": False, "mood": "cerebral", "intensity": "moderate"},
    1422: {"name": "Filmmaking", "category": "Theme-Other", "isAdult": False},
    1427: {"name": "Prison", "category": "Setting-Scene", "isAdult": False},
    1433: {"name": "Marriage", "category": "Theme-Other", "isAdult": False, "mood": "emotional"},
    1446: {"name": "Zoophilia", "category": "Sexual Content", "isAdult": True},
    1450: {"name": "Male Pregnancy", "category": "Sexual Content", "isAdult": True},
    1453: {"name": "Desert", "category": "Setting-Scene", "isAdult": False},
    1455: {"name": "Fairy", "category": "Cast-Traits", "isAdult": False},
    1456: {"name": "Femboy", "category": "Cast-Traits", "isAdult": False},
    1459: {"name": "Polyamorous", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    1489: {"name": "Boarding School", "category": "Setting-Scene", "isAdult": False},
    1490: {"name": "Proxy Battle", "category": "Theme-Other", "isAdult": False, "mood": "hype"},
    1492: {"name": "Board Game", "category": "Theme-Game", "isAdult": False, "mood": "sporty"},
    1501: {"name": "Natural Disaster", "category": "Setting-Scene", "isAdult": False, "intensity": "moderate"},
    1511: {"name": "Double Penetration", "category": "Sexual Content", "isAdult": True},
    1515: {"name": "Pet Play", "category": "Sexual Content", "isAdult": True},
    1523: {"name": "Inn", "category": "Setting-Scene", "isAdult": False},
    1525: {"name": "Horticulture", "category": "Theme-Slice of Life", "isAdult": False, "mood": "chill", "intensity": "light"},
    1526: {"name": "Matriarchy", "category": "Setting", "isAdult": False},
    1537: {"name": "Coastal", "category": "Setting-Scene", "isAdult": False},
    1539: {"name": "Unrequited Love", "category": "Theme-Romance", "isAdult": False, "mood": "emotional", "intensity": "moderate"},
    1544: {"name": "Mountaineering", "category": "Theme-Other", "isAdult": False, "mood": "adventurous"},
    1564: {"name": "Estranged Family", "category": "Cast-Main Cast", "isAdult": False, "mood": "emotional", "intensity": "moderate"},
    1571: {"name": "Office", "category": "Setting-Scene", "isAdult": False},
    1573: {"name": "Cervix Penetration", "category": "Sexual Content", "isAdult": True},
    1574: {"name": "Veterinarian", "category": "Cast-Traits", "isAdult": False},
    1578: {"name": "Arranged Marriage", "category": "Cast-Traits", "isAdult": False, "mood": "emotional"},
    1589: {"name": "Criminal Organization", "category": "Theme-Other-Organisations", "isAdult": False, "intensity": "moderate"},
    1591: {"name": "Hair Pulling", "category": "Sexual Content", "isAdult": True},
    1596: {"name": "Time Loop", "category": "Theme-Sci-Fi", "isAdult": False},
    1598: {"name": "Ancient China", "category": "Setting-Time", "isAdult": False},
    1601: {"name": "Primarily Animal Cast", "category": "Cast-Main Cast", "isAdult": False},
    1607: {"name": "Konbini", "category": "Setting-Scene", "isAdult": False},
    1612: {"name": "Acrobatics", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    1615: {"name": "Hip-hop Music", "category": "Theme-Arts-Music", "isAdult": False},
    1616: {"name": "Snowscape", "category": "Setting-Scene", "isAdult": False},
    1624: {"name": "Matchmaking", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    1632: {"name": "Bowling", "category": "Theme-Game-Sport", "isAdult": False, "mood": "sporty"},
    1645: {"name": "Parenthood", "category": "Theme-Slice of Life", "isAdult": False, "mood": "chill", "intensity": "light"},
    1647: {"name": "Restaurant", "category": "Setting-Scene", "isAdult": False},
    1648: {"name": "Cowboys", "category": "Cast-Traits", "isAdult": False},
    1653: {"name": "Mating Press", "category": "Sexual Content", "isAdult": True},
    1657: {"name": "Fake Relationship", "category": "Theme-Drama", "isAdult": False, "mood": "emotional"},
    1659: {"name": "Fisting", "category": "Sexual Content", "isAdult": True},
    1666: {"name": "Elderly Protagonist", "category": "Cast-Main Cast", "isAdult": False},
    1667: {"name": "Eco-Horror", "category": "Theme-Drama", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    1670: {"name": "Psychosexual", "category": "Theme-Other", "isAdult": False, "mood": "emotional", "intensity": "moderate"},
    1672: {"name": "Jazz Music", "category": "Theme-Arts-Music", "isAdult": False},
    1673: {"name": "Classical Music", "category": "Theme-Arts-Music", "isAdult": False},
    1674: {"name": "Rock Music", "category": "Theme-Arts-Music", "isAdult": False, "intensity": "moderate"},
    1675: {"name": "Metal Music", "category": "Theme-Arts-Music", "isAdult": False, "intensity": "heavy"},
    1681: {"name": "Aromantic", "category": "Cast-Traits", "isAdult": False},
    1689: {"name": "Curses", "category": "Theme-Fantasy", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    1690: {"name": "Vocal Synth", "category": "Theme-Other", "isAdult": False},
    1709: {"name": "Cheating", "category": "Sexual Content", "isAdult": True},
    1719: {"name": "Exorcism", "category": "Theme-Fantasy", "isAdult": False, "mood": "dark"},
    1722: {"name": "Erotic Piercings", "category": "Sexual Content", "isAdult": True},
    1724: {"name": "Camping", "category": "Setting-Scene", "isAdult": False, "mood": "chill", "intensity": "light"},
    1732: {"name": "Shimaidon", "category": "Sexual Content", "isAdult": True},
    1742: {"name": "Mixed Media", "category": "Technical", "isAdult": False},
    1745: {"name": "Rescue", "category": "Theme-Other", "isAdult": False, "mood": "adventurous"},
    1752: {"name": "Medieval", "category": "Setting-Time", "isAdult": False},
    1753: {"name": "Cohabitation", "category": "Theme-Romance", "isAdult": False, "mood": "emotional"},
    1760: {"name": "Wilderness", "category": "Setting-Scene", "isAdult": False, "mood": "adventurous"},
    1771: {"name": "Creature Taming", "category": "Theme-Other", "isAdult": False},
    1779: {"name": "Body Image", "category": "Theme-Other", "isAdult": False, "mood": "emotional", "intensity": "moderate"},
    1788: {"name": "Indigenous Cultures", "category": "Theme-Other", "isAdult": False},
    1789: {"name": "Long Strip", "category": "Technical", "isAdult": False},
    1790: {"name": "Vertical Video", "category": "Technical", "isAdult": False},
    1807: {"name": "Fingering", "category": "Sexual Content", "isAdult": True},
    1813: {"name": "Gekiga", "category": "Technical", "isAdult": False},
    1835: {"name": "Manzai", "category": "Theme-Arts", "isAdult": False, "mood": "funny", "intensity": "light"},
    1848: {"name": "Modeling", "category": "Theme-Arts", "isAdult": False},
    1866: {"name": "Kabuki", "category": "Theme-Arts", "isAdult": False},
    1867: {"name": "Ballet", "category": "Theme-Arts", "isAdult": False, "mood": "sporty"},
    1891: {"name": "Single-Page Chapter", "category": "Technical", "isAdult": False},
    1899: {"name": "Brainwashing", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
    1902: {"name": "Swapping ", "category": "Sexual Content", "isAdult": True},
    1903: {"name": "Oyakodon", "category": "Sexual Content", "isAdult": True},
    1907: {"name": "Reverse Isekai", "category": "Theme-Fantasy", "isAdult": False, "mood": "adventurous"},
    1908: {"name": "Graduation Project", "category": "Technical", "isAdult": False},
    1923: {"name": "Human Experimentation", "category": "Theme-Other", "isAdult": False, "mood": "dark", "intensity": "heavy"},
}
# fmt: on

NSFW_TAGS = {tag["name"] for _, tag in ALL_TAGS.items() if tag["isAdult"]}

TAG_BY_NAME = {info["name"]: info for info in ALL_TAGS.values()}

ALL_GENRES = {
    "Action": {"mood": "hype"},
    "Adventure": {"mood": "adventurous"},
    "Comedy": {"mood": "funny", "intensity": "light"},
    "Drama": {"mood": "emotional", "intensity": "heavy"},
    "Ecchi": {},
    "Fantasy": {"mood": "adventurous"},
    "Hentai": {},
    "Horror": {"mood": "dark", "intensity": "heavy"},
    "Mahou Shoujo": {},
    "Mecha": {"mood": "hype"},
    "Music": {"mood": "emotional"},
    "Mystery": {"mood": "cerebral", "intensity": "moderate"},
    "Psychological": {"mood": "cerebral", "intensity": "heavy"},
    "Romance": {"mood": "emotional"},
    "Sci-Fi": {"mood": "adventurous"},
    "Slice of Life": {"mood": "chill", "intensity": "light"},
    "Sports": {"mood": "sporty"},
    "Supernatural": {},
    "Thriller": {"mood": "dark", "intensity": "heavy"},
}

ALL_FEATURES = set(ALL_GENRES.keys()).union(ALL_TAGS.keys())
