MAL_DATA = {
    "data": [
        {
            "node": {
                "id": 30,
                "title": "Neon Genesis Evangelion",
                "main_picture": {
                    "medium": "https://api-cdn.myanimelist.net/images/anime/1314/108941.jpg",
                    "large": "https://api-cdn.myanimelist.net/images/anime/1314/108941l.jpg",
                },
                "nsfw": "white",
                "genres": [
                    {"id": 1, "name": "Action"},
                    {"id": 5, "name": "Avant Garde"},
                    {"id": 46, "name": "Award Winning"},
                    {"id": 8, "name": "Drama"},
                    {"id": 18, "name": "Mecha"},
                    {"id": 40, "name": "Psychological"},
                    {"id": 24, "name": "Sci-Fi"},
                    {"id": 41, "name": "Suspense"},
                ],
                "my_list_status": {
                    "status": "completed",
                    "score": 10,
                    "num_episodes_watched": 26,
                    "is_rewatching": False,
                    "updated_at": "2013-08-09T06:11:09+00:00",
                    "tags": [],
                },
                "media_type": "tv",
            }
        },
        {
            "node": {
                "id": 270,
                "title": "Hellsing",
                "main_picture": {
                    "medium": "https://api-cdn.myanimelist.net/images/anime/10/19956.jpg",
                    "large": "https://api-cdn.myanimelist.net/images/anime/10/19956l.jpg",
                },
                "nsfw": "white",
                "genres": [
                    {"id": 1, "name": "Action"},
                    {"id": 50, "name": "Adult Cast"},
                    {"id": 58, "name": "Gore"},
                    {"id": 14, "name": "Horror"},
                    {"id": 42, "name": "Seinen"},
                    {"id": 37, "name": "Supernatural"},
                    {"id": 32, "name": "Vampire"},
                ],
                "my_list_status": {
                    "status": "completed",
                    "score": 8,
                    "num_episodes_watched": 13,
                    "is_rewatching": False,
                    "updated_at": "2017-05-26T18:32:10+00:00",
                    "tags": [],
                },
                "media_type": "tv",
            }
        },
    ]
}


ANIME_OFFLINE_DATA = {
    "data": [
        {
            "sources": [
                "https://anidb.net/anime/1243",
                "https://anilist.co/anime/589",
                "https://anime-planet.com/anime/silver-fang",
                "https://anisearch.com/anime/2633",
                "https://kitsu.io/anime/544",
                "https://livechart.me/anime/5107",
                "https://myanimelist.net/anime/589",
                "https://notify.moe/anime/2Q_ocKmiR",
            ],
            "title": "Ginga Nagareboshi Gin",
            "type": "TV",
            "episodes": 21,
            "status": "FINISHED",
            "animeSeason": {"season": "SPRING", "year": 1986},
            "picture": "https://cdn.myanimelist.net/images/anime/3/47461.jpg",
            "thumbnail": "https://cdn.myanimelist.net/images/anime/3/47461t.jpg",
            "synonyms": [
                "EzüstNyíl",
                "Ging: The Falling Star",
                "Ginga: Nagareboshi Gin",
                "Hopeanuoli",
                "Silver Fang",
                "Silver Fang: Shooting Star Gin",
                "Silverfang",
                "The small hero. Birth of Gin",
                "gng",
                "المخلب الفضي",
                "銀牙 -流れ星 銀-",
                "銀牙 流れ星銀",
                "銀牙　流れ星銀",
            ],
            "relations": [
                "https://anidb.net/anime/3449",
                "https://anilist.co/anime/915",
                "https://anime-planet.com/anime/ginga-densetsu-weed",
                "https://anisearch.com/anime/937",
                "https://kitsu.io/anime/815",
                "https://myanimelist.net/anime/915",
                "https://notify.moe/anime/IWW1cKmig",
            ],
            "tags": [
                "action",
                "adventure",
                "animal protagonists",
                "animals",
                "anthropomorphic",
                "based on a manga",
                "bears",
                "cannibalism",
                "dogs",
                "drama",
                "friendship",
                "manga",
                "ninja",
                "non-human protagonists",
                "present",
                "primarily male cast",
                "revenge",
                "shounen",
                "violence",
                "war",
            ],
        },
        {
            "sources": [
                "https://anidb.net/anime/1009",
                "https://anilist.co/anime/2150",
                "https://anime-planet.com/anime/delightful-moomin-family",
                "https://anisearch.com/anime/818",
                "https://kitsu.io/anime/1946",
                "https://livechart.me/anime/5667",
                "https://myanimelist.net/anime/2150",
                "https://notify.moe/anime/we9YcKmiR",
            ],
            "title": "Tanoshii Muumin Ikka",
            "type": "TV",
            "episodes": 78,
            "status": "FINISHED",
            "animeSeason": {"season": "SPRING", "year": 1990},
            "picture": "https://cdn.myanimelist.net/images/anime/13/26765.jpg",
            "thumbnail": "https://cdn.myanimelist.net/images/anime/13/26765t.jpg",
            "synonyms": [
                "Adventures from Moominvalley",
                "Delightful Moomin Family",
                "Die Mumins",
                "Fun Family Moomin",
                "I Mumindalen",
                "Les Moomins",
                "Les moomins",
                "Los Moomin",
                "Los Moomins",
                "Los Mumins",
                "Moomin",
                "Moomin (1990)",
                "Moominland, un mondo di serenità",
                "Muminki",
                "Mumins",
                "Mumintroll",
                "Mumitroldene",
                "Mummitrollet",
                "Mumínci",
                "Muumilaakson tarinoita",
                "Muumin",
                "Muumioru lood",
                "Muumit",
                "Múmínálfarnir",
                "TMI",
                "Tales From Moominvalley",
                "Tanoshii Moomin Ikka",
                "Tanoshī Mūmin Ikka",
                "The Moomins",
                "The Tales from Moominvalley",
                "The Tales of Moomin Valley",
                "Troliai Mumiai",
                "Οι Μούμιν",
                "Приключения муми-троллей",
                "המומינים",
                "وادي الأمان",
                "たのしいむーみんいっか",
                "小肥肥一族",
                "楽しいムーミン一家",
                "무민 잉글리쉬",
                "무민 잉글리시",
            ],
            "relations": [
                "https://anidb.net/anime/1008",
                "https://anidb.net/anime/1010",
                "https://anidb.net/anime/3570",
                "https://anilist.co/anime/2313",
                "https://anilist.co/anime/5712",
                "https://anilist.co/anime/8234",
                "https://anilist.co/anime/8235",
                "https://anime-planet.com/anime/comet-in-moominland",
                "https://anime-planet.com/anime/moomin",
                "https://anime-planet.com/anime/moomin-1972",
                "https://anime-planet.com/anime/tanoshii-moomin-ikka-bouken-nikki",
                "https://anisearch.com/anime/16",
                "https://anisearch.com/anime/2029",
                "https://kitsu.io/anime/2095",
                "https://kitsu.io/anime/4253",
                "https://kitsu.io/anime/5258",
                "https://kitsu.io/anime/5259",
                "https://livechart.me/anime/11264",
                "https://livechart.me/anime/6955",
                "https://livechart.me/anime/9122",
                "https://myanimelist.net/anime/2313",
                "https://myanimelist.net/anime/5712",
                "https://myanimelist.net/anime/8234",
                "https://myanimelist.net/anime/8235",
                "https://notify.moe/anime/ewTEcFmmg",
                "https://notify.moe/anime/gj_jcFmiR",
                "https://notify.moe/anime/uZWitKiig",
                "https://notify.moe/anime/wemmpFmmR",
            ],
            "tags": [
                "acting",
                "adventure",
                "aliens",
                "alternative world",
                "amnesia",
                "animal protagonists",
                "anthropomorphism",
                "classic literature",
                "comedy",
                "dragons",
                "drawing",
                "episodic",
                "family friendly",
                "family life",
                "fantasy",
                "fantasy world",
                "iyashikei",
                "kids",
                "kodomo",
                "mermaid",
                "monster",
                "monster boy",
                "non-human protagonists",
                "novel",
                "outdoor",
                "philosophy",
                "pirates",
                "police",
                "rural",
                "slice of life",
                "tomboy",
                "travel",
                "witch",
            ],
        },
    ]
}
